# runtime: python27
# api_version: 1
# threadsafe: false

# handlers:
# - url: /
#   script: index.py


runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)